### ISSUE TITLE
There is no artifact in maven central repo

### ISSUE THREAD

**Issue by navneetpandey** [airbrake/logback#1]
Hi,

It seems there is no artifact for io.airbrake.logback in maven central repo. https://mvnrepository.com/artifact/io.airbrake

Am I missing something or it is yet to upload?

**Comment by vmihailenco** [comment]
Please use JCentral repository for now. We are in process of uploading artifacts to maven central, but it is not ready yet.

**Comment by vmihailenco** [comment]
Should be available in Maven Central too.
