### ISSUE TITLE
Upload v0.1.1 to Maven Central

### ISSUE THREAD

**Issue by keelerm84** [airbrake/logback#7]
v0.1.1 is available on jCenter but not Maven Central. Given that [jCenter is shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), can you publish the most recent release to Maven Central instead?

**Comment by phumpal** [comment]
@keelerm84 we can most certainly look into this. @scottsbaldwin FYI

**Comment by thompiler** [comment]
>...can you publish the most recent release to Maven Central instead?


The current release is v0.1.6 and is available on Maven Central:
https://search.maven.org/artifact/io.airbrake/javabrake/0.1.6/jar

Does that address your request or did you want v0.1.1 to be available on Maven Central?

<img width="891" alt="Screen Shot 2021-02-25 at 11 17 04 AM" src="https://user-images.githubusercontent.com/2172513/109205288-3f243980-775b-11eb-8531-fd39fb1b78f4.png">

**Comment by thompiler** [comment]
Ah, my mistake, that's the main javabrake repo. I see you are referencing the logback integration where v0.1.1 is the latest version. 👍

**Comment by thompiler** [comment]
Version 0.1.1 should be available now on Maven Central. It usually takes a little bit to show up in the search results but it can be accessed directly:

https://search.maven.org/artifact/io.airbrake/logback/0.1.1/jar

Thanks and let us know if you have any other questions/issues.
